# Generated by Django 3.2 on 2022-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pub_name', models.CharField(max_length=200)),
                ('pub_phone', models.CharField(max_length=200)),
                ('pub_email', models.CharField(max_length=200)),
                ('animal_type', models.CharField(max_length=200)),
                ('animal_location', models.CharField(max_length=200)),
                ('animal_freetext', models.CharField(max_length=200)),
                ('animal_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
