# Generated by Django 3.2 on 2022-05-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_lostpet_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
