# Generated by Django 3.2 on 2022-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_lostpet_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
