# Generated by Django 3.2 on 2022-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='animal_status',
            field=models.CharField(default='LOST', max_length=200),
            preserve_default=False,
        ),
    ]
