# Generated by Django 3.2 on 2022-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_lostpet_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
