# Generated by Django 3.2 on 2022-05-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_lostpet_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='animal_image',
            field=models.ImageField(upload_to='media/uploads/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('freetext', models.CharField(max_length=10000)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.lostpet')),
            ],
        ),
    ]
